import os
from PIL import Image

files = os.listdir(r"C:\Users\kerba\Documents\programs\CS-10\About me site testing ground\public\images")

for fileName in files:
	if fileName.endswith(".jpg") and "_thumb" not in fileName:
		pageName = fileName.removesuffix(".jpg")
		if pageName + ".html" not in files: #Don't re-create the file all over again if we already made it
			print(f"Making file {pageName}")
			with open("public\\images\\" + pageName + ".html", "w") as page:
				page.write(f"""
<!-- This code was generated by a python script based on html code I wrote -->
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="imgstyle.css"> <!-- Use stylesheet links to avoid repeated code on different pages-->
	<title>28add11.win</title>
</head>

<body>
<div class="wrapper"> <!-- wrapper div for formatting -->

	<div class="navbar">
		<a href="../">28add11.win</a>
		<a href="../imgs.html">Images</a>
		<a href="../blag.html">Blog</a>
		<a href="../programming.html">Programming</a>
	</div>

	<div class="content">
		<a href="{fileName}"> <!-- Except on very large screens, clicking this will link to a full-res version -->
			<img src="{fileName}">
		</a>
	</div>

	<div class="footer">
		<footer>
			<p xmlns:cc="http://creativecommons.org/ns#" >This work is licensed under <a href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"></a></p>
		</footer>
	</div>

</div>
</body>""")
				
		if pageName + "_thumb.jpg" not in files: #if a thumb version of the img doesnt exist
			img = Image.open("public/images/" + fileName)
			aspectRatio = img.width / img.height

			img.thumbnail((180 * aspectRatio, 180))
			img.save("public/images/" + pageName + "_thumb.jpg", format="jpeg", quality=80, optimize=1)

			img.show()
			altTxt = input(f"Enter alt text for {pageName}: ")

			with open(r"public\imgs.html", "r") as imgpage:
				imgHTML = imgpage.read()
			suffix = """
		</div>
	</div>

	<div class="footer">
		<footer>
			Copyright 2023 Nicholas West
		</footer>
	</div>

</div>
</body>
"""
			imgHTML = imgHTML[:-119] # We can just get rid of the footer lmao

			outputHTML = imgHTML + f"""
			<a href="images/{pageName}.html" class="image_links">
				<img src=images/{pageName + "_thumb.jpg"} width="{img.width}" height="180" alt="{altTxt}" loading="lazy">
			</a>""" + suffix

			with open(r"public\imgs.html", "w") as imgpage:
				imgpage.write(outputHTML)